services:
  docdepot:
  # TAGS: 'latest', 'stable' or dedicated git commit hash 
    image: ghcr.io/tna76874/docdepot:latest
    ports:
      - "5000:5000"
    container_name: docdepot-container
    environment:
      - DOCDEPOT_API_KEY=test
      - DOCDEPOT_SHOW_INFO=False
      - DOCDEPOT_SHOW_RESPONSE_TIME=False
      - DOCDEPOT_SHOW_TIMESTAMP=False
      - DOCDEPOT_MODEL=data/model.keras
    volumes:
      - ./data:/app/data
