version: '3'
services:
  docdepot:
    image: ghcr.io/tna76874/docdepot:stable
    ports:
      - "5000:5000"
    container_name: docdepot-container
    environment:
      - DOCDEPOT_API_KEY=test
      - DOCDEPOT_SHOW_INFO=False
      - DOCDEPOT_SHOW_RESPONSE_TIME=False
      - DOCDEPOT_SHOW_TIMESTAMP=False
    volumes:
      - ./data:/app/data