name: Build Docker Image

on:
  push:
    branches:
      - master
      - main
      - stable
    paths:
      - '**'
      - '!Dockerfile_base'
      - '!requirements.txt'
  pull_request:
    branches:
      - master
      - main
    paths:
      - '**'
      - '!Dockerfile_base'
      - '!requirements.txt'

jobs:
  build-image:
    runs-on: ubuntu-latest
    needs: build-base
    steps:
      - uses: actions/checkout@v3

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Docker image
        run: ./build.sh Dockerfile

  dummy-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is a dummy job to satisfy GitHub Actions requirement"
